# API sncf via navitia


@endpointsncf = {{$dotenv SNCF_API_URL_SNCF}}
@endpointnavitia = {{$dotenv SNCF_API_URL_NAVITIA}}

@tokenNavitia = {{$dotenv SNCF_API_TOKEN_NAVITIA}}
@tokenSNCF = {{$dotenv SNCF_API_TOKEN_SNCF}}

### ROOT sncf
GET {{ endpointsncf }}/

### ROOT navitia
GET {{ endpointnavitia }}/

### Le détail des modes de transport couvert par l’API
GET {{ endpointsncf }}/coverage/sncf/commercial_modes
Authorization: {{tokenSNCF}}

### Tous les points d'arrêt sncf
GET {{ endpointsncf }}/coverage/sncf/stop_areas
Authorization: {{tokenSNCF}}

### Itinéraires entre Paris et Lyon
GET {{ endpointsncf }}/coverage/sncf/journeys?from=admin:fr:75056&to=admin:fr:69123&datetime=20230511
Authorization: {{tokenSNCF}}

### Prochains départs à Montparnasse
GET {{ endpointsncf }}/coverage/sncf/stop_areas/stop_area:SNCF:87391003/departures?datetime=20230511
Authorization: {{tokenSNCF}}

### Itinéraires à partir de Paris
GET {{ endpointsncf }}/coverage/sncf/journeys?from=admin:fr:75056&datetime=20230511&max_duration=3600
Authorization: {{tokenSNCF}}

### autocomplete on geographical data to find the departure and destination points from an input text
GET {{endpointnavitia}}/places?q=de%20lyon&type[]=address&type[]=stop_area
Authorization: {{tokenNavitia}}

### test itinéraires de Paris avec première section en vélo
GET {{ endpointnavitia }}/journeys?from=admin:fr:75056&first_section_mode[]=bike
Authorization: {{tokenNavitia}}

### Ne fonctionne pas
### je veux : pas de tspt sans vélo, vélo start and end, sortir de ma ville/département
GET {{ endpointnavitia }}/journeys?from=2.37825371181375;48.84915325462162
Authorization: {{tokenNavitia}}
# &first_section_mode[]=bike&last_section_mode[]=bike&datetime=20230511180000&max_duration=10800&forbidden_uris[physical_mode:Air]&forbidden_uris[physical_mode:Boat]&forbidden_uris[physical_mode:Bus]&forbidden_uris[physical_mode:BusRapidTransit]&forbidden_uris[physical_mode:Coach]&forbidden_uris[physical_mode:Funicular]&forbidden_uris[physical_mode:Metro]&forbidden_uris[physical_mode:Shuttle]&forbidden_uris[physical_mode:SuspendedCableCar]&forbidden_uris[physical_mode:Taxi]


### list of stop_areas
GET {{ endpointsncf }}/coverage/sncf/stop_areas/
Authorization: {{tokenSNCF}}

### Autour de Paris
GET {{endpointsncf}}/coverage/sncf/places?q=paris&type[]=address
Authorization: {{tokenSNCF}}

### Places autres que SNCF avec token NAVITIA
GET {{endpointnavitia}}/places?q=New%20York&type[]=address
Authorization: {{tokenNavitia}}

### Journeys en fonction d'une place avec token NAVITIA
GET {{endpointnavitia}}/journeys?from=2.37825371181375%3B48.84915325462162&datetime=20230517T140000&max_duration=1200
Authorization: {{tokenNavitia}}

### Journey détaillé choisi dans la liste des suggestions
GET {{endpointnavitia}}/journeys?from=2.37825371181375%3B48.84915325462162&datetime=20230517T140000&max_duration=1200&to=stop_point%3AIDFM%3A24976
Authorization: {{tokenNavitia}}
