# TESTS search auto-complete

# Base URL
@endpoint = http://localhost:{{$dotenv PORT}}

# Token du user connecté
@authorization = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY4NDc0Mzk0MCwiZXhwIjoxNjg1MzQ4NzQwfQ.NGFUkwgq2OTIyvGdQOvHN4tq5U9JTAUdBqPZAL94n4Y

### 404
GET {{ endpoint }}/search
Authorization: {{ authorization }}

#########################
#         SEARCH        #
#########################

### Obtenir des places existantes en auto-complete
GET {{ endpoint }}/autocomplete/aligre
Authorization: {{ authorization }}
# ATTENDU : url = /autocomplete/<les caracteres recherchés>
# RENVOI : results = {id: string, name: string}[]

### Obtenir des itineraires par filtre
GET {{ endpoint }}/journey/search?from=2.3786875;48.8486506&datetime=20230603T120000&max_duration=3600
Authorization: {{ authorization }}
# ATTENDU : url = /journey/search 
#           & req.query = {from: string, datetime: string(YYYYMMDDThhmmss), max_duration: integer(seconds)}
# RENVOI : results = {
#    departure_date_time: string(YYYYMMDDThhmmss),
#    duration: integer(seconds),
#    from: {
#        id: string,
#        name: string,
#    },
#    to: {
#        id: string,
#        name: string,
#    },
#    nb_transfers: integer,
#    queryUrl:string
# }[]

### Obtenir le détail d'un itinéraire sélectionné
GET {{ endpoint }}/journey/detail?from=-2.1048366%3B47.115432899999995&datetime=20230603T120000&max_duration=7200&to=stop_point%3AP44%3A44PORTecomA
Authorization: {{ authorization }}
# ATTENDU : url = /journey/detail/ + journey.queryUrl
# RENVOI : results = {
#    departure_date_time: string(YYYYMMDDThhmmss),
#    arrival_date_time: string(YYYYMMDDThhmmss),
#    duration: integer(seconds),
#    nb_transfers: integer,
#    from: {
#        id: string,
#        name: string,
#    },
#    to: {
#        id: string,
#        name: string,
#    },
#    sections: {
#       departure_date_time: string(YYYYMMDDThhmmss),
#       arrival_date_time: string(YYYYMMDDThhmmss),
#       duration: integer(seconds),
#       nb_transfers: integer,
#       from: {
#           id: string,
#           name: string,
#       },
#       to: {
#           id: string,
#           name: string,
#       },
#       transportMode: string
#    }[]
#   }