################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################

@endpoint = http://localhost:{{$dotenv PORT}}

### 404
GET {{ endpoint }}/userss

#########################
#         SIGNUP        #
#########################

### Créer un user avec email déja existant
POST {{ endpoint }}/signup
content-type: application/json

{
  "email": "pierre@gmail.com",
  "password": "Jjbesos-1234",
  "passwordCheck": "Jjbesos-1234",
  "firstname": "Jean",
  "lastname": "Jacques",
  "acceptedConditions": true
}

### Créer un user
POST {{ endpoint }}/signup
content-type: application/json

{
  "email": "jeanjacques@gmail.com",
  "password": "Jjbesos-1234",
  "passwordCheck": "Jjbesos-1234",
  "firstname": "Jean",
  "lastname": "Jacques",
  "acceptedConditions": true
}

#########################
#         LOGIN         #
#########################

### Login en erreur email
POST {{ endpoint }}/login
content-type: application/json

{
  "email": "pierrefzerfzre@gmail.com",
  "password": "Jjbesos-1234"
}

### Login en erreur password
POST {{ endpoint }}/login
content-type: application/json

{
  "email": "pierre@gmail.com",
  "password": "Bcde!1234"
}

### Login
POST {{ endpoint }}/login
content-type: application/json

{
  "email": "jeanjacques@gmail.com",
  "password": "Jjbesos-1234"
}

#########################
#         USERS         #
#########################

### Récupérér les infos du user signedin
GET {{ endpoint }}/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJqZWFuamFjcXVlc0BnbWFpbC5jb20iLCJmaXJzdG5hbWUiOiJKZWFuIiwibGFzdG5hbWUiOiJKYWNxdWVzIiwiYWNjZXB0ZWRfY29uZGl0aW9ucyI6dHJ1ZSwiY3JlYXRlZF9hdCI6IjIwMjMtMDUtMTBUMTQ6Mjg6NDQuMzY4WiIsInVwZGF0ZWRfYXQiOiIyMDIzLTA1LTEwVDE0OjI4OjQ0LjM2OFoiLCJpYXQiOjE2ODM3Mjg5MjQsImV4cCI6MTY4NDMzMzcyNH0.QbB8ShQEaQic9rFEp9EGULMg1THT3sx39b2nRk8p9Rw

### Modifier le user signedin avec un email déja utilisé
PATCH {{ endpoint }}/user
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJqZWFuamFjcXVlc0BnbWFpbC5jb20iLCJmaXJzdG5hbWUiOiJKZWFuIiwibGFzdG5hbWUiOiJKYWNxdWVzIiwiYWNjZXB0ZWRfY29uZGl0aW9ucyI6dHJ1ZSwiY3JlYXRlZF9hdCI6IjIwMjMtMDUtMTBUMTQ6Mjg6NDQuMzY4WiIsInVwZGF0ZWRfYXQiOiIyMDIzLTA1LTEwVDE0OjI4OjQ0LjM2OFoiLCJpYXQiOjE2ODM3Mjg5MjQsImV4cCI6MTY4NDMzMzcyNH0.QbB8ShQEaQic9rFEp9EGULMg1THT3sx39b2nRk8p9Rw

{
  "email": "pierre@gmail.com"
}

### Modifier l'email du user signedin
PATCH {{ endpoint }}/user
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJqZWFuamFjcXVlc0BnbWFpbC5jb20iLCJmaXJzdG5hbWUiOiJKZWFuIiwibGFzdG5hbWUiOiJKYWNxdWVzIiwiYWNjZXB0ZWRfY29uZGl0aW9ucyI6dHJ1ZSwiY3JlYXRlZF9hdCI6IjIwMjMtMDUtMTBUMTQ6Mjg6NDQuMzY4WiIsInVwZGF0ZWRfYXQiOiIyMDIzLTA1LTEwVDE0OjI4OjQ0LjM2OFoiLCJpYXQiOjE2ODM3Mjg5MjQsImV4cCI6MTY4NDMzMzcyNH0.QbB8ShQEaQic9rFEp9EGULMg1THT3sx39b2nRk8p9Rw

{
  "email": "testing89@hotmail.com"
}

### Modifier le password (attention à la conformité) et le firstname du user signedin
PATCH {{ endpoint }}/user
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJqZWFuamFjcXVlc0BnbWFpbC5jb20iLCJmaXJzdG5hbWUiOiJKZWFuIiwibGFzdG5hbWUiOiJKYWNxdWVzIiwiYWNjZXB0ZWRfY29uZGl0aW9ucyI6dHJ1ZSwiY3JlYXRlZF9hdCI6IjIwMjMtMDUtMTBUMTQ6Mjg6NDQuMzY4WiIsInVwZGF0ZWRfYXQiOiIyMDIzLTA1LTEwVDE0OjI4OjQ0LjM2OFoiLCJpYXQiOjE2ODM3Mjg5MjQsImV4cCI6MTY4NDMzMzcyNH0.QbB8ShQEaQic9rFEp9EGULMg1THT3sx39b2nRk8p9Rw

{
  "password": "Superpassword-99",
  "firstname": "Jean-Pascal"
}

### Supprimer le user signedin
DELETE {{ endpoint }}/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJqZWFuamFjcXVlc0BnbWFpbC5jb20iLCJmaXJzdG5hbWUiOiJKZWFuIiwibGFzdG5hbWUiOiJKYWNxdWVzIiwiYWNjZXB0ZWRfY29uZGl0aW9ucyI6dHJ1ZSwiY3JlYXRlZF9hdCI6IjIwMjMtMDUtMTBUMTQ6Mjg6NDQuMzY4WiIsInVwZGF0ZWRfYXQiOiIyMDIzLTA1LTEwVDE0OjI4OjQ0LjM2OFoiLCJpYXQiOjE2ODM3Mjg5MjQsImV4cCI6MTY4NDMzMzcyNH0.QbB8ShQEaQic9rFEp9EGULMg1THT3sx39b2nRk8p9Rw

#########################
#       FAVORITE        #
#########################

### Liste des favoris
GET {{ endpoint }}/favorite
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJqZWFuamFjcXVlc0BnbWFpbC5jb20iLCJmaXJzdG5hbWUiOiJKZWFuIiwibGFzdG5hbWUiOiJKYWNxdWVzIiwiYWNjZXB0ZWRfY29uZGl0aW9ucyI6dHJ1ZSwiY3JlYXRlZF9hdCI6IjIwMjMtMDUtMTBUMTQ6Mjg6NDQuMzY4WiIsInVwZGF0ZWRfYXQiOiIyMDIzLTA1LTEwVDE0OjI4OjQ0LjM2OFoiLCJpYXQiOjE2ODM3Mjg5MjQsImV4cCI6MTY4NDMzMzcyNH0.QbB8ShQEaQic9rFEp9EGULMg1THT3sx39b2nRk8p9Rw

### Créer un favori
POST {{ endpoint }}/favorite
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJqZWFuamFjcXVlc0BnbWFpbC5jb20iLCJmaXJzdG5hbWUiOiJKZWFuIiwibGFzdG5hbWUiOiJKYWNxdWVzIiwiYWNjZXB0ZWRfY29uZGl0aW9ucyI6dHJ1ZSwiY3JlYXRlZF9hdCI6IjIwMjMtMDUtMTBUMTQ6Mjg6NDQuMzY4WiIsInVwZGF0ZWRfYXQiOiIyMDIzLTA1LTEwVDE0OjI4OjQ0LjM2OFoiLCJpYXQiOjE2ODM3Mjg5MjQsImV4cCI6MTY4NDMzMzcyNH0.QbB8ShQEaQic9rFEp9EGULMg1THT3sx39b2nRk8p9Rw

{
    "origin": "TestUserOneIsLoggedIn",
    "destination": "EssaiUserOneIsLoggedIn",
    "comment": "NoCommentUserOneIsLoggedIn",
    "journey_time": 56789
}

### Récupérér un favori par son id
GET {{ endpoint }}/favorite/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJqZWFuamFjcXVlc0BnbWFpbC5jb20iLCJmaXJzdG5hbWUiOiJKZWFuIiwibGFzdG5hbWUiOiJKYWNxdWVzIiwiYWNjZXB0ZWRfY29uZGl0aW9ucyI6dHJ1ZSwiY3JlYXRlZF9hdCI6IjIwMjMtMDUtMTBUMTQ6Mjg6NDQuMzY4WiIsInVwZGF0ZWRfYXQiOiIyMDIzLTA1LTEwVDE0OjI4OjQ0LjM2OFoiLCJpYXQiOjE2ODM3Mjg5MjQsImV4cCI6MTY4NDMzMzcyNH0.QbB8ShQEaQic9rFEp9EGULMg1THT3sx39b2nRk8p9Rw

### Modifier un favori
PATCH {{ endpoint }}/favorite/3
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJqZWFuamFjcXVlc0BnbWFpbC5jb20iLCJmaXJzdG5hbWUiOiJKZWFuIiwibGFzdG5hbWUiOiJKYWNxdWVzIiwiYWNjZXB0ZWRfY29uZGl0aW9ucyI6dHJ1ZSwiY3JlYXRlZF9hdCI6IjIwMjMtMDUtMTBUMTQ6Mjg6NDQuMzY4WiIsInVwZGF0ZWRfYXQiOiIyMDIzLTA1LTEwVDE0OjI4OjQ0LjM2OFoiLCJpYXQiOjE2ODM3Mjg5MjQsImV4cCI6MTY4NDMzMzcyNH0.QbB8ShQEaQic9rFEp9EGULMg1THT3sx39b2nRk8p9Rw

{
    "comment": "Commentaire du user_id 1 Ok ça marche"
}

### Supprimer un favori par son id
DELETE {{ endpoint }}/favorite/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJqZWFuamFjcXVlc0BnbWFpbC5jb20iLCJmaXJzdG5hbWUiOiJKZWFuIiwibGFzdG5hbWUiOiJKYWNxdWVzIiwiYWNjZXB0ZWRfY29uZGl0aW9ucyI6dHJ1ZSwiY3JlYXRlZF9hdCI6IjIwMjMtMDUtMTBUMTQ6Mjg6NDQuMzY4WiIsInVwZGF0ZWRfYXQiOiIyMDIzLTA1LTEwVDE0OjI4OjQ0LjM2OFoiLCJpYXQiOjE2ODM3Mjg5MjQsImV4cCI6MTY4NDMzMzcyNH0.QbB8ShQEaQic9rFEp9EGULMg1THT3sx39b2nRk8p9Rw
