################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################

# Base URL
@endpoint = http://localhost:{{$dotenv PORT}}
@tokenDePierre = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY4NDE2MTI2MywiZXhwIjoxNjg0NzY2MDYzfQ.0DGt8YAZLq_L5JjuSPHHZ3xS56rfJ0sfhlcsDS2ouDc
@tokenDeJean = 

# Token du user connecté
@authorization = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTY4NDIyNjE2MCwiZXhwIjoxNjg0ODMwOTYwfQ.g64TjLgTkIpyQjJflUD6Frnt-wzqTYKOc2PRTJVMOB4

### 404
GET {{ endpoint }}/usersss
Authorization: {{ authorization }}

#########################
#         SIGNUP        #
#########################

### Créer un user avec email déja existant
POST {{ endpoint }}/signup
content-type: application/json

{
  "email": "pierre@gmail.com",
  "password": "Jjbesos-1234",
  "firstname": "Jean",
  "lastname": "Jacques",
  "acceptedConditions": true
}

### Créer un user
POST {{ endpoint }}/signup
content-type: application/json

{
  "email": "jeanjacques@gmail.com",
  "password": "Jjbesos-1234",
  "firstname": "Jean",
  "lastname": "Jacques",
  "acceptedConditions": true
}

#########################
#         LOGIN         #
#########################

### Login du nouveau compte créé
POST {{ endpoint }}/login
content-type: application/json

{
  "email": "jeanjacques@gmail.com",
  "password": "Jjbesos-1234"
}

### Login d'un compte seedé
POST {{ endpoint }}/login
content-type: application/json

{
  "email": "pierre@gmail.com",
  "password": "Bcde!1234"
}

### Login en erreur email
POST {{ endpoint }}/login
content-type: application/json

{
  "email": "pierree@gmail.com",
  "password": "Bcde!1234"
}
### Login en erreur password
POST {{ endpoint }}/login
content-type: application/json

{
  "email": "pierre@gmail.com",
  "password": "Bcde!1235"
}

#########################
#         USERS         #
#########################

### Récupérér les infos du user signedin
GET {{ endpoint }}/user
Authorization: Bearer {{tokenDePierre}}

### Modifier le user signedin avec un email déja utilisé
PATCH {{ endpoint }}/user
content-type: application/json
Authorization: Bearer {{tokenDePierre}}

{
  "email": "jeanjacques@gmail.com"
}

### Modifier l'email du user signedin
PATCH {{ endpoint }}/user
content-type: application/json
Authorization: Bearer {{tokenDePierre}}

{
  "email": "testing89@hotmail.com"
}

### Modifier le password (attention à la conformité) et le firstname du user signedin
PATCH {{ endpoint }}/user
content-type: application/json
Authorization: Bearer {{tokenDePierre}}

{
  "password": "Superpassword99",
  "firstname": "Jean-Pascal"
}

### Supprimer le user signedin
DELETE {{ endpoint }}/user
Authorization: Bearer {{tokenDeJean}}

#########################
#       FAVORITE        #
#########################

### Liste des favoris
GET {{ endpoint }}/favorite
Authorization: Bearer {{tokenDePierre}}

### Créer un favori
POST {{ endpoint }}/favorite
content-type: application/json
Authorization: Bearer {{tokenDePierre}}

{
    "origin": "TestUserOneIsLoggedIn",
    "destination": "EssaiUserOneIsLoggedIn",
    "comment": "NoCommentUserOneIsLoggedIn",
    "journey_time": 56789
}

### Récupérér un favori par son id
GET {{ endpoint }}/favorite/5
Authorization: Bearer {{tokenDePierre}}

### Modifier un favori
PATCH {{ endpoint }}/favorite/3
content-type: application/json
Authorization: Bearer {{tokenDePierre}}

{
    "comment": "Commentaire du user_id 1 Ok ça marche"
}

### Supprimer un favori par son id
DELETE {{ endpoint }}/favorite/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY4MzkxMjYwOCwiZXhwIjoxNjg0NTE3NDA4fQ.CMvDRLqy6KD4Dt29EHlLeymnlDnlahAe4GsqPOL3h-8


