# TESTS search auto-complete

# Base URL
@endpoint = http://localhost:{{$dotenv PORT}}
@endpointProd = https://bikeend-api.up.railway.app

# Token du user connecté
@authorization = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTY4NDc2NzUwNCwiZXhwIjoxNjg1MzcyMzA0fQ.Uw8_DSE5C_V6anBM46JmZi69tv6hce7oCj2w-k3fL0s

### 404
GET {{ endpoint }}/search
Authorization: {{ authorization }}

#########################
#         SEARCH        #
#########################

### Obtenir des places existantes en auto-complete
GET {{ endpoint }}/autocomplete/aligre
Authorization: {{ endpointProd }}
# ATTENDU : url = /autocomplete/<les caracteres recherchés>
# RENVOI : results = {id: string, name: string}[]

### Obtenir des itineraires par filtre
GET {{ endpointProd }}/journey/search?from=2.3793433;48.8504715&datetime=20230603T120000&max_duration=3600&per_page=10&current_page=20
Authorization: {{ authorization }}
# ATTENDU : url = /journey/search 
#           & req.query = {from: string, datetime: string(YYYYMMDDThhmmss), max_duration: integer(seconds)}
# RENVOI : results = {
#    departure_date_time: string(YYYYMMDDThhmmss),
#    duration: integer(seconds),
#    from: {
#        id: string,
#        name: string,
#    },
#    to: {
#        id: string,
#        name: string,
#    },
#    nb_transfers: integer,
#    queryUrl:string
# }[]

### Obtenir le détail d'un itinéraire sélectionné
GET {{ endpoint }}/journey/detail?from=-2.1048366%3B47.115432899999995&datetime=20230603T120000&max_duration=7200&to=stop_point%3AP44%3A44PORTecomA
Authorization: {{ authorization }}
# ATTENDU : url = /journey/detail/ + journey.queryUrl
# RENVOI : results = {
#    departure_date_time: string(YYYYMMDDThhmmss),
#    arrival_date_time: string(YYYYMMDDThhmmss),
#    duration: integer(seconds),
#    nb_transfers: integer,
#    from: {
#        id: string,
#        name: string,
#    },
#    to: {
#        id: string,
#        name: string,
#    },
#    sections: {
#       departure_date_time: string(YYYYMMDDThhmmss),
#       arrival_date_time: string(YYYYMMDDThhmmss),
#       duration: integer(seconds),
#       nb_transfers: integer,
#       from: {
#           id: string,
#           name: string,
#       },
#       to: {
#           id: string,
#           name: string,
#       },
#       transportMode: string
#    }[]
#   }